"""Layout metrics — tune sizes in one place."""

from __future__ import annotations

# Window
WINDOW_DEFAULT_W = 1440
WINDOW_DEFAULT_H = 900
WINDOW_MIN_W = 1120
WINDOW_MIN_H = 720

# Sidebar
SIDEBAR_MIN_W = 380
SIDEBAR_MAX_W = 520
SIDEBAR_SPLIT_W = 420

# Controls
BTN_HEIGHT = 38
BTN_HEIGHT_PRIMARY = 46
BTN_HEIGHT_COMPACT = 34
INPUT_MIN_HEIGHT = 34
LIST_ITEM_MIN_HEIGHT = 56
TABLE_ROW_HEIGHT = 30

# Areas
FILE_LIST_MIN_H = 72
FILE_LIST_PREF_H = 112
LOG_MIN_H = 100
LOG_PREF_H = 140
PREVIEW_MIN_H = 320

# Spacing
CARD_PADDING = 16
CARD_SPACING = 12
SECTION_SPACING = 14
